# Generated by Django 4.0.4 on 2022-08-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orderitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
    ]
